// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPhotos() {
  return window['go']['main']['App']['GetPhotos']();
}

export function ImportFromFolder(arg1) {
  return window['go']['main']['App']['ImportFromFolder'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function UpdatePhotoDate(arg1, arg2) {
  return window['go']['main']['App']['UpdatePhotoDate'](arg1, arg2);
}
