// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAutomationLogs() {
  return window['go']['main']['App']['GetAutomationLogs']();
}

export function GetDiagnostics() {
  return window['go']['main']['App']['GetDiagnostics']();
}

export function GetPhotos() {
  return window['go']['main']['App']['GetPhotos']();
}

export function GetPhotosPaged(arg1, arg2) {
  return window['go']['main']['App']['GetPhotosPaged'](arg1, arg2);
}

export function GetThumbnail(arg1) {
  return window['go']['main']['App']['GetThumbnail'](arg1);
}

export function ImportFromFolder(arg1) {
  return window['go']['main']['App']['ImportFromFolder'](arg1);
}

export function LogFrontendError(arg1) {
  return window['go']['main']['App']['LogFrontendError'](arg1);
}

export function LogUIState(arg1) {
  return window['go']['main']['App']['LogUIState'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SendCommand(arg1, arg2) {
  return window['go']['main']['App']['SendCommand'](arg1, arg2);
}

export function SetThumbnailHandler(arg1) {
  return window['go']['main']['App']['SetThumbnailHandler'](arg1);
}

export function UpdatePhotoDate(arg1, arg2) {
  return window['go']['main']['App']['UpdatePhotoDate'](arg1, arg2);
}
