// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetPhotos():Promise<Array<models.Photo>>;

export function ImportFromFolder(arg1:string):Promise<number>;

export function SelectFolder():Promise<string>;

export function UpdatePhotoDate(arg1:number,arg2:string):Promise<void>;
