// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {library} from '../models';

export function GetAutomationLogs():Promise<Record<string, any>>;

export function GetDiagnostics():Promise<Record<string, any>>;

export function GetPhotos():Promise<Array<models.Photo>>;

export function GetPhotosPaged(arg1:number,arg2:number):Promise<Array<models.Photo>>;

export function GetThumbnail(arg1:string):Promise<string>;

export function ImportFromFolder(arg1:string):Promise<number>;

export function LogFrontendError(arg1:string):Promise<void>;

export function LogUIState(arg1:string):Promise<void>;

export function SelectFolder():Promise<string>;

export function SendCommand(arg1:string,arg2:any):Promise<void>;

export function SetThumbnailHandler(arg1:library.ThumbnailHandler):Promise<void>;

export function UpdatePhotoDate(arg1:number,arg2:string):Promise<void>;
